### ISSUE TITLE
Upgrade webaudiocontrols please, they include know a midi learn right click menu

### ISSUE THREAD

**Issue by micbuffa** [nicroto/viktor-nv1-engine#3]
If you upgrade your webaudiocontrols.html file (from: https://github.com/g200kg/webaudio-controls), then you'll get a right click menu with midilearn built-in. Just add the attribute midilearn=true like that  &lt;webaudio-knob midilearn=true ... &gt; and that's all :-) It works with knobs, switches, sliders.

![polymer webaudio-controls live demo 2017-04-26 23-48-26](https://cloud.githubusercontent.com/assets/648664/25566958/f47f7a62-2de3-11e7-8fc8-bf9eb877e375.jpg)

**Comment by nicroto** [comment]
Thanks, but this repository has nothing to do with the UI. Please, add this as an issue on the UI repo.

**Comment by micbuffa** [comment]
I just wanted to inform you that the webaudiocontrols lib you use has been updated. If your rebuild your synth in order to use the last version, and add a midilearn=true to `<web-audio-knob midilearn=true>`, you'll get a right click context menu, making the GUI of Viktor-NV1 midi controllable. Having your online demo midi controllable (knobs, sliders, switches) would be interesting...
